name: Build and Publish IG package to ACC Nexus
on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: accnewzealand/ig-publisher:1.6.15
      credentials:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set Java Heap Space
        run: |
          echo "export JAVA_TOOL_OPTIONS='-Xmx2g'" >> $GITHUB_ENV

      - name: Copy shell script file
        run: |
          mkdir -p /apps/icp
          cp -r * /apps/icp/
          chmod +x /apps/icp/build-publish.sh

      - name: Run shell script
        run: |
          /apps/icp/build-publish.sh

      - name: Create package.json
        run: |
          cd /apps/icp/package
          echo '{
            "name": "icp",
            "version": "1.1.43",
            "publishConfig": {
                "registry": "https://nexus.ds.acc.co.nz/repository/npm-integration"
            },
            "repository":"https://github.com/integration-services-accnz/icp",
            "canonical": "http://hl7.org.nz/fhir/icp",
            "url": "http://hl7.org.nz/fhir/icp",
            "title": "New Zealand ICP Implementation Guide",
            "description": "The ICP facade",
            "language": "en",
            "author": "ACC Integration",
            "maintainers": [
                {
                    "name": "ACC Integration",
                    "email": "digitaloperations@acc.co.nz"
                }
            ],
            "license": "CC0-1.0"
          }' > package.json

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: /apps/icp/package

  publish:
    needs: build
    runs-on:
      group: release-general-linux
    permissions:
      packages: read
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ github.event.workflow_run.id }}
          name: build-artifacts

      - name: Login via Az module
        uses: azure/login@v2
        with:
          creds: ${{secrets.AZURE_CREDENTIALS_PROD}}
          enable-AzPSSession: true

      - name: Get nexus secrets from Azure Key Vault
        shell: bash
        run: |-
          for secret_name in  prdnexususer prdnexustoken; do
            secret_value=$(az keyvault secret show --vault-name "SYD-PDD-KVT-INT-NONPROD" --name $secret_name --query value -o tsv)
            echo "::add-mask::$secret_value"
            echo "$secret_name=$secret_value" >> $GITHUB_ENV
          done

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Set .npmrc to private for publishing
        run: |
          npm config set registry="https://nexus.ds.acc.co.nz/repository/npm-integration/"
          encoded_string=$(echo -n "${{env.prdnexususer}}":"${{env.prdnexustoken}}" | base64)
          npm config set //nexus.ds.acc.co.nz/repository/npm-integration/:_auth="$encoded_string"

          touch .npmrc
          echo "registry=https://nexus.ds.acc.co.nz/repository/npm-integration/" >> /.npmrc
          echo "//nexus.ds.acc.co.nz/repository/npm-integration/:_auth=$encoded_string" >> /.npmrc

      - name: Publish to ACC Nexus Package Registry
        run: |
          npm publish
